import type { StudioState, StudioAction } from '../types/state';
import { initialStudioState } from '../types/state';
import { createDefaultPage } from '../types/dashboard';
import { pagesReducer, visualsReducer, textBoxesReducer, dataModelReducer, uiReducer, filtersReducer } from './reducers';

// Actions that are handled by sub-reducers
const PAGE_ACTIONS = new Set<string>([
  'ADD_PAGE', 'DUPLICATE_PAGE', 'REMOVE_PAGE', 'RENAME_PAGE', 'SET_ACTIVE_PAGE',
  'REORDER_PAGES', 'SET_PAGE_SIZE', 'SET_PAGE_BACKGROUND', 'SET_PAGE_BACKGROUND_IMAGE',
]);

const VISUAL_ACTIONS = new Set<string>([
  'ADD_VISUAL', 'REMOVE_VISUAL', 'REMOVE_SELECTED_VISUALS',
  'BRING_VISUAL_TO_FRONT', 'SEND_VISUAL_TO_BACK',
  'DUPLICATE_VISUAL', 'DUPLICATE_SELECTED_VISUALS',
  'SELECT_VISUAL', 'SELECT_VISUAL_MULTI', 'SELECT_ALL_VISUALS',
  'ALIGN_VISUALS', 'DISTRIBUTE_VISUALS',
  'MOVE_VISUAL', 'MOVE_SELECTED_VISUALS', 'RESIZE_VISUAL',
  'UPDATE_VISUAL', 'NUDGE_VISUAL',
  'BRING_TO_FRONT', 'SEND_TO_BACK', 'BRING_FORWARD', 'SEND_BACKWARD',
  'TOGGLE_VISUAL_LOCK', 'TOGGLE_VISUAL_HIDDEN', 'TOGGLE_LOCK_ALL',
  'SET_CLIPBOARD', 'PASTE_VISUAL',
  'REORDER_VISUALS',
  'SET_CROSS_FILTER', 'CLEAR_CROSS_FILTER', 'DRILL_DOWN', 'DRILL_UP',
  'GROUP_SELECTED_VISUALS', 'UNGROUP_SELECTED_VISUALS',
  'SET_BUCKET_FIELD', 'REMOVE_BUCKET_FIELD', 'REORDER_BUCKET_FIELDS',
]);

const TEXTBOX_ACTIONS = new Set<string>([
  'ADD_TEXT_BOX', 'REMOVE_TEXT_BOX', 'UPDATE_TEXT_BOX', 'SELECT_TEXT_BOX',
  'MOVE_TEXT_BOX', 'RESIZE_TEXT_BOX', 'BRING_TEXT_BOX_TO_FRONT', 'SEND_TEXT_BOX_TO_BACK',
]);

const DATAMODEL_ACTIONS = new Set<string>([
  'SET_DATA_MODEL', 'TOGGLE_RELATIONSHIP_ACTIVE', 'SET_DATA_MODEL_LOADING', 'SET_DATA_MODEL_ERROR',
  'SET_QUERY_RESULT',
  'SELECT_MEASURE', 'ADD_MEASURE', 'UPDATE_MEASURE', 'REMOVE_MEASURE',
  'ADD_MEASURE_FOLDER', 'RENAME_MEASURE_FOLDER', 'REMOVE_MEASURE_FOLDER',
  'OPEN_CALCULATED_COLUMN_EDITOR', 'CLOSE_CALCULATED_COLUMN_EDITOR',
  'ADD_CALCULATED_COLUMN', 'UPDATE_CALCULATED_COLUMN', 'REMOVE_CALCULATED_COLUMN',
  'OPEN_CALCULATED_TABLE_EDITOR', 'CLOSE_CALCULATED_TABLE_EDITOR',
  'ADD_CALCULATED_TABLE', 'UPDATE_CALCULATED_TABLE', 'REMOVE_CALCULATED_TABLE',
  'SET_MODEL_VIEW_TABS', 'SET_ACTIVE_MODEL_VIEW_TAB', 'ADD_MODEL_VIEW_TAB',
  'RENAME_MODEL_VIEW_TAB', 'REMOVE_MODEL_VIEW_TAB', 'UPDATE_MODEL_VIEW_TAB',
  'ADD_TABLE_TO_MODEL', 'REMOVE_TABLE_FROM_MODEL', 'ADD_RELATIONSHIP',
  'RENAME_TABLE', 'RENAME_FIELD', 'HIDE_FIELD', 'UNHIDE_FIELD',
  'AUTO_DETECT_RELATIONSHIPS', 'UPDATE_RELATIONSHIP', 'REMOVE_RELATIONSHIP',
]);

const UI_ACTIONS = new Set<string>([
  'LOAD_DASHBOARD', 'SET_DASHBOARD_NAME', 'SET_DASHBOARD_DESCRIPTION', 'MARK_CLEAN',
  'UNDO', 'REDO', 'PUSH_SNAPSHOT',
  'SET_ACTIVE_VIEW', 'TOGGLE_DATA_PANEL', 'TOGGLE_PROPERTIES_PANEL', 'TOGGLE_FILTERS_PANEL',
  'COLLAPSE_DATA_PANEL', 'COLLAPSE_PROPERTIES_PANEL', 'COLLAPSE_FILTERS_PANEL',
  'COLLAPSE_SELECTION_PANE', 'EXPAND_SELECTION_PANE', 'EXPAND_DATA_PANEL',
  'EXPAND_PROPERTIES_PANEL', 'EXPAND_FILTERS_PANEL', 'TOGGLE_SELECTION_PANE',
  'SET_DATA_PANEL_WIDTH', 'SET_PROPERTIES_PANEL_WIDTH', 'SET_FILTERS_PANEL_WIDTH',
  'SET_CANVAS_ZOOM', 'TOGGLE_GRID', 'SET_MODE',
  'SAVE_DASHBOARD', 'SET_SAVING', 'SET_LAST_SAVED_AT',
  'FOCUS_VISUAL', 'EXIT_FOCUS_MODE',
  'SET_PENDING_FILTER_DROP',
  'OPEN_MEASURE_EDITOR', 'CLOSE_MEASURE_EDITOR',
  'OPEN_IMPORT_DIALOG', 'CLOSE_IMPORT_DIALOG', 'SET_SQL_RUNNER_STATE',
  'TOGGLE_SIDEBAR',
]);

const FILTER_ACTIONS = new Set<string>([
  'SET_GLOBAL_FILTERS', 'SET_PAGE_FILTERS', 'SET_VISUAL_FILTERS',
  'TOGGLE_SYNCED_FILTER', 'APPLY_SYNCED_FILTERS',
]);

export function studioReducer(state: StudioState, action: StudioAction): StudioState {
  const type = action.type;

  if (PAGE_ACTIONS.has(type)) return pagesReducer(state, action);
  if (VISUAL_ACTIONS.has(type)) return visualsReducer(state, action);
  if (TEXTBOX_ACTIONS.has(type)) return textBoxesReducer(state, action);
  if (DATAMODEL_ACTIONS.has(type)) return dataModelReducer(state, action);
  if (UI_ACTIONS.has(type)) return uiReducer(state, action);
  if (FILTER_ACTIONS.has(type)) return filtersReducer(state, action);

  return state;
}

export function getInitialState(mode: 'editor' | 'viewer' = 'editor'): StudioState {
  const defaultPage = createDefaultPage();
  return {
    ...initialStudioState,
    mode,
    pages: [defaultPage],
    activePageId: defaultPage.id,
  };
}
